---

- hosts: all
  become: true
  tasks:

  - name: Ubuntu - update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Ubuntu - remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: Ubuntu - remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"



  - name: CentOS - update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: CentOS - remove apache2 package
    dnf:
      name: httpd
      state: absent
    when: ansible_distribution == "CentOS"

  - name: CentOS - remove php support for apache
    dnf:
      name: php
      state: absent
    when: ansible_distribution == "CentOS"