---

- hosts: all
  become: true
  tasks:

  - name: Remove apache and PHP
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes